---
title: "Publications"
author: Roberto Cantillan
layout: single-sidebar
date: "2023-08-10"
---

On this page, you will find the results of projects I was involved in and submitted to review by experts. They are all in APA format. Each document includes a link to access the PDF. Soon, I will link them to their respective OSF code repositories.

---

Garreton, M., Espinoza, V., & Cantillan, R. (2021). Social capital in the urban context: Diversity and social contacts in Chilean cities. _Journal of Urban Affairs_, 0(0), 1–20. [https://doi.org/10.1080/07352166.2021.1974302](https://doi.org/10.1080/07352166.2021.1974302)
[<i class="fa-solid fa-file-pdf"></i>](pdf/Social-capital-urban-context.pdf)

Plaza, A., Cantillan, R., Beck, G., & Espinoza, V. (2022). Juntos, pero no revueltos: Homofilia en relaciones intergrupales mapuche y no-mapuche. _Revista de Sociología_, 37(1). [https://doi.org/10.5354/0719-529X.2022.68147](https://doi.org/10.5354/0719-529X.2022.68147)
[<i class="fa-solid fa-file-pdf"></i>](pdf/document.pdf)

Cantillan, R., & Herrera, J. (2020). Centralidad de actores y bloques en las redes organizativas de movilización en el conflicto por el Plan Regulador Comunal de Peñalolén el año 2011. _Revista EURE - Revista de Estudios Urbano Regionales_, 46(138). [http://www.eure.cl/index.php/eure/article/view/3035](http://www.eure.cl/index.php/eure/article/view/3035)
[<i class="fa-solid fa-file-pdf"></i>](pdf/3035-20945-2-PB.pdf)







**Batailler, C.**, Brannon, S. M., Teas, P. E., & Gawronski, B. (2021). A signal detection approach to understandingthe identification of fake news. _Perspectives on Psychological Science_, 174569162098613. [10.1177/1745691620986135](https://doi.org/10.1177/1745691620986135)  
[<i class="fa-solid fa-file-pdf"></i>](pdf/2021_BBTG_PPS.pdf)
[<i class="ai ai-osf"></i>](https://osf.io/uc9me/)

**Batailler, C.**, Muller, D., Nurra, C., Rougier, M., & Trouilloud, D. (2021). Math approach training changes implicitidentification with math: A close preregistered replication. _Journal of Experimental Social Psychology_, _92_, 104059. [10.1016/j.jesp.2020.104059](https://doi.org/10.1016/j.jesp.2020.104059)  
[<i class="fa-solid fa-file-pdf"></i>](pdf/2021_BMNRT_JESP.pdf)
[<i class="ai ai-osf"></i>](https://osf.io/pcea3)

Rougier, M., Muller, D., Courset, R., Smeding, A., Devos, T., & **Batailler, C**. (2020). Toward the use of approach/avoidancetendencies as attitude measures: Individual- and group-level variability of the ingroup bias. _European Journal of Social Psychology_, ejsp.2653. [10.1002/ejsp.2653](https://doi.org/10.1002/ejsp.2653)  
[<i class="fa-solid fa-file-pdf"></i>](pdf/2020_RMCSDB_EJSP.pdf)

