---
author: Cantillan, R.
categories:
- talks
date: "2023-08-16"
draft: false
event: 
event_url: 
excerpt: 
featured: true
layout: single
links:
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/rcantillan/slides/tree/main/mobility_class
- icon: door-open
  icon_pack: fas
  name: Slides
  url: https://rcantillan.github.io/slides/mobility_class/
location: DEMOSAL, Buenos Aires. 
show_post_time: false
title: Clases de movilidad en Chile 2009 - 2020
---

En este trabajo se concibe la estructura ocupacional como un sistema adaptativo de intercambio generalizado (Bearman, 1997). En esta interpretación, diversas ocupaciones con atributos dinámicos se entrelazan a través del movimiento de trabajadores, un fenómeno que responde tanto a influencias externas inesperadas como a procesos internos de la propia red.

Esta visión nos permite visualizar el mercado ocupacional como una red direccional y valorada, donde las ocupaciones conforman los nodos y los flujos de trabajadores funcionan como los enlaces. A través de estos enlaces, se transmiten oportunidades y restricciones que configuran el panorama laboral (Cheng & Park, 2020).

El objetivo es ambicioso: describir la estructura emergente del mercado ocupacional de manera compleja y dinámica, focalizando en las conexiones entre ocupaciones, los desplazamientos de trabajadores y los procesos de contagio entre ocupaciones a lo largo del tiempo en un intervalo de diez años en el contexto chileno.

Además, al examinar la trayectoria de los individuos a través de distintas ocupaciones, se revelarán patrones que arrojarán luz sobre los cambios y las continuidades en la composición de la fuerza laboral en Chile. Esta exploración va más allá de meras estadísticas, abordando los matices y las narrativas que emergen de estas trayectorias profesionales entrelazadas.

&nbsp;
&nbsp;

```{r echo=FALSE}
options(htmltools.dir.version = TRUE)
xaringanExtra::embed_xaringan("https://rcantillan.github.io/slides/mobility_class/", ratio = "16:9")
```

&nbsp;
&nbsp;

### Bibliográfia

- Bearman, P. (1997). Generalized Exchange. American Journal of Sociology, 102(5), 1383–1415. https://doi.org/10.1086/231087

- Cheng, S., & Park, B. (2020). Flows and Boundaries: A Network Approach to Studying Occupational Mobility in the Labor Market. American Journal of Sociology, 126(3), 577–631. https://doi.org/10.1086/712406

- Lin, K.-H., & Hung, K. (2022). The Network Structure of Occupations: Fragmentation, Differentiation, and Contagion. American Journal of Sociology, 127(5), 1551–1601. https://doi.org/10.1086/719407















