---
author: Cantillan, R.
categories:
- talks
date: "2023-08-01"
date_end: "2023-08-08"
draft: false
event: 
event_url: 
excerpt: 
featured: true
layout: single
links:
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/rcantillan/slides/tree/main/ciencias-sociales-computacionales
- icon: door-open
  icon_pack: fas
  name: Slides
  url: https://rcantillan.github.io/slides/ciencias-sociales-computacionales/intro/#1
location: Universidad Católica del Maule (Online)
show_post_time: false
title: Investigación social en la era digital
---

El transcurso de la era de la información y las transformaciones tecnológicas que la acompañan conllevan oportunidades y retos inéditos para el progreso de la investigación social. Nos encontramos en un momento en el cual podemos observar y analizar el comportamiento humano de formas radicalmente novedosas y prometedoras. El propósito de este ciclo breve de diálogos es acercar a los participantes a estas innovadoras modalidades de investigación y al potencial inherente a las denominadas "ciencias sociales computacionales". Las conversaciones estarán dirigidas hacia las novedosas estrategias de diseño de investigaciones sociales, considerando las nuevas fuentes de información disponibles y la influencia actual de la capacidad computacional. El contenido de la presentación esta basado en el libro "Bit by Bit" de Matthew Salganik.  

&nbsp;
&nbsp;

### Recursos extras para la profundización. 

1.[R para Ciencia de Datos](https://es.r4ds.hadley.nz/) (versión en español) by Hadley Wickham and Garrett Grolemund
&nbsp;
2.[Introduction to Computational Social Science](https://bookdown.org/markhoff/css/) by Mark Hoffman
&nbsp;
3.[Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham
&nbsp;
4.[Bit By Bit](https://www.bitbybitbook.com/) By Matthew Salganik
&nbsp;
5.[Summer Institute for Computational Social Science](https://sicss.io/)

&nbsp;
&nbsp;

### Slides

```{r echo=FALSE}
options(htmltools.dir.version = TRUE)
xaringanExtra::embed_xaringan("https://rcantillan.github.io/slides/ciencias-sociales-computacionales/intro/", ratio = "16:9")
```

&nbsp;
&nbsp;












