baseURL = "https://rcantillan.rbind.io/"
 
languageCode = 'en-us'
title = 'Roberto Cantillan'

theme = 'apero'

ignoreFiles = [ "\\.qmd$", "\\.ipynb$" ]

googleAnalytics = "G-CSC1TRYSDL"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "github"

[imaging]
  quality = 70
  resampleFilter = "Lanczos"

# HUGO-APERO SETTINGS ---------------------------------------------------------
[params]
  orgName = "Roberto Cantillan"
  logo = "/img/logo2.png"

  mainSections = ["blog", "projects", "pubs"]
  navallcaps = true

  # TODO: update social sharing image
  # Default image for social sharing and search engines. 
  # Place image file in `static` folder and specify image name here.
  sharing_image = "/img/papillons.jpg"
  # Twitter username (without @). Used when a visitor shares your site on Twitter.
  twitter = "ricantillan"

  # use a built-in color theme
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water
  theme = "peach"
  
  # or, leave theme empty & make your own palette
  # see docs at https://hugo-apero.netlify.app/learn/color-themes/
  # the custom scss file must be in the assets/ folder
  # add the filename name here, without extension
  # to use hex colors instead of named tachyons colors, include "hex" in filename
  custom_theme = "hex-colors" 

  # use an embedded font
  customtextFontFamily = "Atkinson Hyperlegible"
  customheadingFontFamily = "Metropolis"
  
  # or choose a system font stack
  textFontFamily = "sans-serif"
  headingFontFamily = "serif"

  [params.utterances]
    use_utterances = true
    repo_name = "rcantillan/rcantillan.rbind.io"
    issue_term = "title" # url, pathname, or title
    theme = "github-light"
    label = "comments :crystal_ball:"

# NAVBAR ----------------------------------------------------------------------
[menu]
  [[menu.header]]
    name = "Notes"
    title = "My project portfolio"
    url = "/blog/"
    weight = 1
  [[menu.header]]
    name = "Projects"
    title = "My project portfolio"
    url = "/projects/"
    weight = 1
  [[menu.header]]
    name = "Pubs"
    title = "My project portfolio"
    url = "/pubs/"
    weight = 2
  [[menu.header]]
    name = "Contact"
    title = "My project portfolio"
    url = "/contact/"
    weight = 3
  
  [[menu.footer]]
    name = "License"
    title = "License"
    url = "/license/"
    weight = 1

[[params.social]]
    icon = "mastodon"
    icon_pack = "fab"
    url = ""
[[params.social]]
    icon      = "github" 
    icon_pack = "fab"
    url       = "https://github.com/rcantillan"
[[params.social]]
    icon      = "linkedin" 
    icon_pack = "fab"
    url       = ""
[[params.social]]
    icon      = "google-scholar" 
    icon_pack = "ai"
    url       = ""
[[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    url = ""
[[params.social]]
    icon      = "cv" 
    icon_pack = "ai"
    url       = ""

# PRIVACY CONTENT -------------------------------------------------------------
# see https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
